# Generated by Django 3.0.8 on 2020-07-25 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200718_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventid', models.AutoField(primary_key=True, serialize=False)),
                ('eventtype', models.CharField(choices=[('MR', 'Marriage'), ('AN', 'Anniversary'), ('BD', 'Birthday'), ('EG', 'Engagment'), ('HW', 'Housewarming')], max_length=2)),
                ('eventdatetimestamp', models.DateTimeField()),
                ('eventdescription', models.TextField()),
                ('venueid', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
