# Generated by Django 3.0.8 on 2020-07-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200728_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventdatetimestamp',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventdescription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venueid',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
