# Generated by Django 3.0.8 on 2020-07-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200728_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventdatetimestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventdescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venueid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
