# Generated by Django 3.0.8 on 2020-07-28 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200728_1542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
